export const productsMock = [
  {
    productId: "1",
    productName: "Faux Suede Mini Skirt",
    productDescription: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    productImg:"/images/product/shelf/product-1.png",
    price: 500,
    sku: [
      { color: "marfim", src: "/images/product/sku/marfim.svg" },
      { color: "rose", src: "/images/product/sku/rose.svg" },
      { color: "blue", src: "/images/product/sku/blue.svg" },
      { color: "ocean", src: "/images/product/sku/ocean.svg" },
    ],
  },
  {
    productId: "2",
    productName: "Ruched Rose Print Mini Skirt",
    productDescription: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    productImg:"/images/product/shelf/product-2.png",
    price: 320,
    sku: [
      { color: "black", src: "/images/product/sku/black.svg" },
      { color: "red", src: "/images/product/sku/red.svg" },
      { color: "beige", src: "/images/product/sku/beige.svg" },
      { color: "off-white", src: "/images/product/sku/off-white.svg" },
    ],
  },
  {
    productId: "1",
    productName: "Faux Suede Mini Skirt",
    productDescription: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    productImg:"/images/product/shelf/product-1.png",
    price: 500,
    sku: [
      { color: "marfim", src: "/images/product/sku/marfim.svg" },
      { color: "rose", src: "/images/product/sku/rose.svg" },
      { color: "blue", src: "/images/product/sku/blue.svg" },
      { color: "ocean", src: "/images/product/sku/ocean.svg" },
    ],
  },
  {
    productId: "2",
    productName: "Ruched Rose Print Mini Skirt",
    productDescription: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    productImg:"/images/product/shelf/product-2.png",
    price: 320,
    sku: [
      { color: "black", src: "/images/product/sku/black.svg" },
      { color: "red", src: "/images/product/sku/red.svg" },
      { color: "beige", src: "/images/product/sku/beige.svg" },
      { color: "off-white", src: "/images/product/sku/off-white.svg" },
    ],
  },
  {
    productId: "1",
    productName: "Faux Suede Mini Skirt",
    productDescription: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    productImg:"/images/product/shelf/product-1.png",
    price: 500,
    sku: [
      { color: "marfim", src: "/images/product/sku/marfim.svg" },
      { color: "rose", src: "/images/product/sku/rose.svg" },
      { color: "blue", src: "/images/product/sku/blue.svg" },
      { color: "ocean", src: "/images/product/sku/ocean.svg" },
    ],
  },
  {
    productId: "2",
    productName: "Ruched Rose Print Mini Skirt",
    productDescription: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    productImg:"/images/product/shelf/product-2.png",
    price: 320,
    sku: [
      { color: "black", src: "/images/product/sku/black.svg" },
      { color: "red", src: "/images/product/sku/red.svg" },
      { color: "beige", src: "/images/product/sku/beige.svg" },
      { color: "off-white", src: "/images/product/sku/off-white.svg" },
    ],
  },
  {
    productId: "1",
    productName: "Faux Suede Mini Skirt",
    productDescription: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    productImg:"/images/product/shelf/product-1.png",
    price: 500,
    sku: [
      { color: "marfim", src: "/images/product/sku/marfim.svg" },
      { color: "rose", src: "/images/product/sku/rose.svg" },
      { color: "blue", src: "/images/product/sku/blue.svg" },
      { color: "ocean", src: "/images/product/sku/ocean.svg" },
    ],
  },
  {
    productId: "2",
    productName: "Ruched Rose Print Mini Skirt",
    productDescription: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    productImg:"/images/product/shelf/product-2.png",
    price: 320,
    sku: [
      { color: "black", src: "/images/product/sku/black.svg" },
      { color: "red", src: "/images/product/sku/red.svg" },
      { color: "beige", src: "/images/product/sku/beige.svg" },
      { color: "off-white", src: "/images/product/sku/off-white.svg" },
    ],
  },
  {
    productId: "1",
    productName: "Faux Suede Mini Skirt",
    productDescription: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    productImg:"/images/product/shelf/product-1.png",
    price: 500,
    sku: [
      { color: "marfim", src: "/images/product/sku/marfim.svg" },
      { color: "rose", src: "/images/product/sku/rose.svg" },
      { color: "blue", src: "/images/product/sku/blue.svg" },
      { color: "ocean", src: "/images/product/sku/ocean.svg" },
    ],
  },
  {
    productId: "2",
    productName: "Ruched Rose Print Mini Skirt",
    productDescription: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    productImg:"/images/product/shelf/product-2.png",
    price: 320,
    sku: [
      { color: "black", src: "/images/product/sku/black.svg" },
      { color: "red", src: "/images/product/sku/red.svg" },
      { color: "beige", src: "/images/product/sku/beige.svg" },
      { color: "off-white", src: "/images/product/sku/off-white.svg" },
    ],
  }
];
